apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-grpc-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: golang-grpc-server
  template:
    metadata:
      labels:
        app: golang-grpc-server
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers: 
      - name: golang-grpc-server
        image: pedroarapua/golang-grpc:v3
        command: ["go"]
        args: ["run", "./helloworld/greeter_server/main.go"]
        ports:
        - containerPort: 80
          protocol: TCP