apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-grpc
  template:
    metadata:
      labels:
        app: golang-grpc
    spec:
      containers: 
      - name: golang-grpc
        image: pedroarapua/golang-grpc:v2
        command: ["go"]
        args: ["run", "./helloworld/greeter_server/main.go"]
        ports:
        - containerPort: 80
          protocol: TCP