apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-grpc
  template:
    metadata:
      labels:
        app: golang-grpc
    spec:
      containers: 
      - args:
        - -Dspring.profiles.active=${ENV}
        - -Dserver.port=5000
        - -jar
        - app.jar
        command:
        - "go"
        - "run"
        - "./helloworld/greeter_server/main.go"
        name: golang-grpc
        image: pedroarapua/golang-grpc:latest
        ports:
        - containerPort: 80
        protocol: TCP