apiVersion: v1
kind: Service
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9200
    targetPort: http
  selector:
    name: elasticsearch