apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-web-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: nodejs-web-app
    spec:     # pod spec                  
      containers: 
      - name: nodejs-web-app
        image: pedroarapua/nodejs-prometheus:nodejs-web-app-latest
        ports:
        - containerPort: 8080