apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-web-app
  template:
    metadata:
      labels:
        app: nodejs-web-app
    spec:
      containers: 
      - name: nodejs-web-app
        image: pedroarapua/nodejs-prometheus:nodejs-web-app-v1
        ports:
        - containerPort: 8080