apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "nodejs-web-app"
        static_configs:
          - targets: ["nodejs-web-app.nodejs-web-app.svc.cluster.local"]