apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-grpc-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-grpc-client
  template:
    metadata:
      labels:
        app: golang-grpc-client
    spec:
      containers: 
      - name: golang-grpc-client
        image: pedroarapua/golang-grpc:v2
        command: ["go"]
        args: ["run", "./helloworld/greeter_client/main.go"]
        env:
        - name: API_URL
          value: golang-grpc-server.golang-grpc:80