apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka-keda
  name: kafka-keda-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-keda-deployment
  template:
    metadata:
      labels:
        app: kafka-keda-deployment
    spec:
      containers: 
      - name: busybox
        image: busybox
        command:
          - sleep
          - "infinity"

---
# Source: base-webapp/templates/keda-hpa.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: kafka-keda
  name: kafka-keda-scale
spec:
  scaleTargetRef:
    name: kafka-keda-deployment
  cooldownPeriod: 60
  pollingInterval: 30
  maxReplicaCount: 5
  minReplicaCount: 0
  triggers:
  - type: kafka
    metadata:
      # bootstrapServers: kafka.kafka.svc.cluster.local:9092
      # consumerGroup: consumer-group
      # topic: teste
      # lagThreshold: '5'
      # offsetResetPolicy: latest
      # allowIdleConsumers: 'false'
      # version: 1.0.0
      lagThreshold: "5"
      topic: "teste"
      bootstrapServers: "kafka.kafka.svc.cluster.local:9092"
      consumerGroup: "consumer-group"
      offsetResetPolicy: "latest"
      allowIdleConsumers: "false"
      scaleToZeroOnInvalidOffset: "false"
      version: "1.0.0"
