apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka-keda
  name: kafka-keda-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-keda-deployment
  template:
    metadata:
      labels:
        app: kafka-keda-deployment
    spec:
      containers: 
      - name: busybox
        image: busybox
        env:
        - name: KEDA_KAFKA_SASL_VALUE
          value: "plaintext"
        - name: KEDA_KAFKA_SASL_USERNAME
          value: "teste"
        command:
          - sleep
          - "infinity"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: kafka-keda
  name: kafka-keda-secret
data:
  KEDA_KAFKA_SASL_PASSWORD: "dGVzdGU="    #teste

---
# Source: base-webapp/templates/keda-hpa.yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  namespace: kafka-keda
  name: kafka-keda-scale
spec:
  scaleTargetRef:
    name: kafka-keda-deployment
  cooldownPeriod: 60
  pollingInterval: 30
  maxReplicaCount: 5
  minReplicaCount: 0
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.kafka.svc.cluster.local:9092
      consumerGroup: consumer-group
      topic: teste
      lagThreshold: '5'
      offsetResetPolicy: latest
      allowIdleConsumers: 'false'
      version: 1.0.0
    authenticationRef:
      name: kafka-keda-trigger
---
# Source: base-webapp/templates/keda-hpa.yaml
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  namespace: kafka-keda
  name: kafka-keda-trigger
spec:
  secretTargetRef:
    - parameter: password
      name: kafka-keda-secret
      key: "KEDA_KAFKA_SASL_PASSWORD"
  env:
    - parameter: sasl
      name: "KEDA_KAFKA_SASL_VALUE"
    - parameter: username
      name: "KEDA_KAFKA_SASL_USERNAME"
